name: Daily Fetch News

on:
  schedule:
    - cron: "0 23 * * *"   # UTC 时间 22 点，对应北京时间早上 6 点
  workflow_dispatch:       # 手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run fetch script
        run: python scripts/fetch_news.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -A   # 注意这里改成 -A，包含新增、修改、删除
          git commit -m "Daily fetch: $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push
